### ISSUE TITLE
`recv()` blocking thread if no packets received preventing clean shutdown

### ISSUE THREAD

**Issue by bornacvitanic** [Rubensei/windivert-rust#11]
This probably isn't a bug, but i'm not sure how to cleanly shut down my thread for receiving packets if there are no incoming packets for the specified filter. The `recv()` call block indefinitely, and force terminating the program makes it so that any followup packet receiving attempts on the same port don't detect any packets (i presume it's because the previous thread was left hanging and is absorbing them all). I saw that there is a shutdown command but that required mutable access to the WinDivert handle which i am not sure how to have if the packet receiving thread either has a Arc reference to it or Arc Mutex but is locking it indeinitely.
If i'm not mistaken `recv_ex()` is also blocking according to the documentation.

**Comment by Rubensei** [comment]
I've been trying to add again the `wait` variants for 0.7.X but I'm having some issues testing the new method implementation and I've experienced a few weird behaviors trying to manually test it.
Programmatically testing blocking operations that require custom test initialization and tricky synchronization is proving to be a bit of a challenge.

> If i'm not mistaken recv_ex() is also blocking according to the documentation.
It's also blocking

**Comment by bornacvitanic** [comment]
Any suggestions for how to work around it in the mean time? I tried using tokio to wait for either the `recv()` or a timeout timer using `select!` to periodically check whether the thread should shut down. That managed to make it so the thread can be cleanly shut down, but after more testing i noticed that in that implementation packets are being missed if they are being sent at a slower pace.
Another idea was to either cache a packet and re-send it as an _impostor_ packet or to generate a new shutdown packet using rusts built in libraries, but to no avail. Neither approach managed to send a packet that the receiving thread was able to catch.
